### ISSUE TITLE
[B incompatible with [C

### ISSUE THREAD

**Issue by sergeig-stcu** [serilogj/serilogj#22]
I've got this error message on JDK 11 (not sure it it is related to JDK 11):

```
java.lang.ClassCastException: [B incompatible with [C
        at io.advantageous.boon.core.reflection.FastStringUtils$StringImplementation$1.toCharArray(FastStringUtils.java:93)
        at io.advantageous.boon.core.reflection.FastStringUtils.toCharArray(FastStringUtils.java:178)
        at io.advantageous.boon.core.Str.underBarCase(Str.java:538)
        at io.advantageous.boon.core.Sys.sysProp(Sys.java:329)
        at io.advantageous.boon.core.timer.TimeKeeperBasic.<init>(TimeKeeperBasic.java:52)
        at io.advantageous.boon.core.Sys.<clinit>(Sys.java:171)
        at io.advantageous.boon.core.reflection.Reflection.<clinit>(Reflection.java:114)
        at serilogj.parameters.PropertyValueConverter.getProperties(PropertyValueConverter.java:209)
        at serilogj.parameters.PropertyValueConverter.createPropertyValue(PropertyValueConverter.java:195)
        at serilogj.parameters.PropertyValueConverter.createPropertyValue(PropertyValueConverter.java:128)
        at serilogj.parameters.PropertyBinder.constructProperty(PropertyBinder.java:100)
        at serilogj.parameters.PropertyBinder.constructNamedProperties(PropertyBinder.java:92)
        at serilogj.parameters.PropertyBinder.constructProperties(PropertyBinder.java:45)
        at serilogj.parameters.MessageTemplateProcessor.process(MessageTemplateProcessor.java:35)
        at serilogj.core.Logger.write(Logger.java:159)
        at serilogj.core.Logger.write(Logger.java:142)
        at serilogj.Log.write(Log.java:133)
```

**Comment by 80dB** [comment]
It's trying to destruct (serialize) something and failing. Not sure what your trying to log at that line. Is it may be a class from a 3rd party library that has been obfuscated?

**Comment by sergeig-stcu** [comment]
Thank you.  That matches my assessment. I use MuleSoft, so its is one of its objects.  I might have to take an option of converting it to string using MuleSoft infrastructure.

**Comment by 80dB** [comment]
What you can also do is create your own IDestructuringPolicy for the specific object. That way you can still keep some properties searchable within Seq.
